#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

wclean BCs
wclean MytwoPhaseMixtureThermo
wclean barotropicCompressibilityModel
wclean rhoCentralDyMFoam

#------------------------------------------------------------------------------
